"""base

Revision ID: 2a95c6b76b8c
Revises: 0
Create Date: 2024-09-09 21:32:35.193632+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a95c6b76b8c"
down_revision: Union[str, None] = "0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("card_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mana_cost", sa.String(length=255), nullable=True),
        sa.Column("rarity", sa.String(length=25), nullable=False),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("toughness", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("set_code", sa.String(length=3), nullable=True),
        sa.Column("scryfall_id", sa.String(), nullable=True, unique=True),
        sa.Column("scryfall_uri", sa.String(), nullable=True),
        sa.Column("card_art_uri", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("card_id"),
        sa.UniqueConstraint("card_id"),
        sa.UniqueConstraint("scryfall_id"),
        sa.UniqueConstraint("scryfall_uri"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card")
    # ### end Alembic commands ###
