# This workflow will install Python dependencies, run tox with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tox

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # cache: "poetry" # some issue here I need to figure out
      - name: Install dependencies
        run: |
          poetry install
      - name: Tox
        run: |
          poetry run tox
